//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MVCPrueba.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Ambiente
    {
        public int idAmbiente { get; set; }
        public string Codigo { get; set; }
        public string NomAmbiente { get; set; }
        public string Descripcion { get; set; }
        public string Caracteristicas { get; set; }
        public Nullable<int> idInstructor { get; set; }
        public Nullable<int> idAprendiz { get; set; }
    
        public virtual Aprendiz Aprendiz { get; set; }
        public virtual Instructor Instructor { get; set; }
    }
}
